[application]
[web.app]
title = "app_treino"

[web.resource]
# Inclua os arquivos CSS explicitamente
style = ["assets/main.css"]

# Inclua o favicon, se necessário
# favicon = "assets/favicon.ico"

[web.resource.dev]
# Para desenvolvimento, se necessário
style = []
script = []

[desktop]
resources = "assets"

[android.app]
name = "App Treino"
display_name = "App Treino"
version_code = 1
version_name = "1.0.0"
min_sdk_version = 21
target_sdk_version = 33

[build]
embed_assets = true
out_dir = "dist"
asset_dir = "assets"
