[application]
[web.app]
title = "app_treino"

[web.resource]
# Inclua os arquivos CSS explicitamente
style = ["assets/main.css"]

# Inclua o favicon, se necessário
# favicon = "assets/favicon.ico"

[web.resource.dev]
# Para desenvolvimento, se necessário
style = []
script = []

[build]
embed_assets = true
out_dir = "dist"
asset_dir = "assets"
